### ISSUE TITLE
Issue with RadListView on activity resume

### ISSUE THREAD

**Issue by quentinor** [telerik/nativescript-ui-feedback#133]
Hi,

First of all, I want to give my thanks to the Telerik team for the RadListView module, it is awesome.
I am developing a  {N} + Angular2 app, and I am using the RadListView Component.

For most cases, it works just fine, but I am experiencing a strange behaviour, and I have spent days trying to figure out where the problem is, yet unsuccessfully.

I have a RadListView with pull to refresh feature, here is the HTML:

```
<RadListView id="listViewFolders"  [items]="dataFolders" style="height: 100%"  pullToRefresh="true" (pullToRefreshInitiated)="onPullToRefreshFolders($event)" >
                <template tkListItemTemplate let-item="item">
                    <StackLayout>
                         <Ripple rippleColor="#cccccc" (tap)="folderTap(item)" *ngIf="isAndroid">
                            <GridLayout rows="*" columns="70,*"  style="border-width:  0 0 1 0; border-color: #efefef;">
                                <StackLayout height="50" width="50" margin="10" verticalAlignment="center" horizontalAlignment="center"
                                             row="0" col="0">
                                    <Image [src]="'res://foldersymbol'"
                                           style="width: 35px; margin-right: 10px; margin-left: 3%" class="loading"></Image>
                                </StackLayout>
                                <StackLayout row="0" col="1" orientation="vertical" horizontalAlignment="left" verticalAlignment="center">
                                    <Label [text]="item.name" horizontalAlignment="left"
                                           style="font-size:16;font-weight: bold; color: #555555">

                                    </Label>
                                    <Label [text]="item.fileAmount + ' Fichiers'" horizontalAlignment="left">

                                    </Label>
                                </StackLayout>
                            </GridLayout>
                        </Ripple>
                    </StackLayout>
                </template>
 </RadListView>
```

and here is the TS: 

```
    ngOnInit() {
        this.getFolders();
    }

    public getFolders() {
        this._documentsService.getFoldersWithFileAmount()
            .then((folders:Array<Folder>) => {
                console.dump(folders);
                this.folders = folders;
                this.dataFolders = new ObservableArray<Folder>(folders);
            })
            .catch((error) => {
                console.log(error);
            });
    }



    public onPullToRefreshFolders(args: ListViewEventData){
        var listView = args.object;

        this._documentsService.getFoldersWithFileAmount()
            .then((folders:Array<Folder>) => {
                this.dataFolders = new ObservableArray<Folder>(folders);
                listView.notifyPullToRefreshFinished();
            })
            .catch((error) => {
                console.log(error);
                listView.notifyPullToRefreshFinished();
            });
    }
    

    getPrettyFileAmount(folder:Folder){
        var amount:number = folder.fileAmount;
        var result =amount.toString();

        if (amount == 0 || amount == 1){
            result=result + ' Fichier'
        }
        else{
            result=result + ' Fichiers'
        }
        return result;

    }

    folderTap(folder:Folder){
        this.navigate('documents/detail/'  + folder.id);
    }

```

The data is obtained through an API
Up to this point, there is not any problem.
The rendered view is :

![screenshot_1490026329](https://cloud.githubusercontent.com/assets/16211927/24109872/42a77450-0d92-11e7-999b-3b0a53488ad0.png)

The trouble starts when I suspend my app, then resume it. After that, the view is now:

![screenshot_1490027291](https://cloud.githubusercontent.com/assets/16211927/24110009/9b7f096c-0d92-11e7-9034-71b7e2187657.png)

Now, each **iteration of the RadListView template is 100% height**, but the behaviour of the list is enchanged, the list still scrolls, the navigation still works...

Moreover, when I pull to refresh, the listView goes back to normal (first screenshot).

I have tested this problem on different templates, and it seems that does not depend on the content of the template. Did I forget something wile implementing the RadListView, or is it a known issue ?

Thanks

**Comment by VladimirAmiorkov** [comment]
Hi @quentinor ,

Can you share with me in what container the RadListView is placed. Due to the nature of the component some layout containers that measure themselves with infinity are not recommended and may experience exactly such issue where each cell of the listview is measure to the max screen space. It is best to place the RadListView inside a `GridLayout`

**Comment by VladimirAmiorkov** [comment]
Also can you share with us the versions of your environment:

- NativeScript version ( tns --version )
- nativescript-telerik-ui version ( check the package.json )

**Comment by quentinor** [comment]
Hi, sorry  for the delay,

NativeScript version  :  **2.5.1**
nativescript-telerik-ui version :  **1.6.1**

I run my app on an emulated Nexus 5X API 24, but I don't think that the device/api level is the source of the problem, because I tested it on many others devices ( real ones ), and the behaviour is still the same.

Concerning the layouts, I wrapped the `GridLayout` inside of a `<StackLayout width="100%" height="100%">  </StackLayout>`, so I will try to use a `GridLayout` just as you suggested.

**Comment by quentinor** [comment]
I found out a lead to explain this behaviour, if I wrap the `RadListView` in a `GridLayout` and I set the height of the `GridLayout` to 200px, for example, when I resume my activty, the height of each item of the ListView is now 200px.

So, it always take the **height of the list's parent**

**Comment by ginev** [comment]
@quentinor this was a known issue with RadListView on Android due to the Google's AppCompat library behavior. We have addressed this issue previously but you seem to have hit another case in which it happens. To be able to understand why and how it happens we would like to ask you for a project that reproduces it - would that be possible?

**Comment by ginev** [comment]
@quentinor - is this still an issue with the latest version of NS UI?

**Comment by shiamalon** [comment]
Hi, 

it is still happening to me but only on a page with router-outlet on IOS.

let me know if you need some code samples or examples.

Regards,

**Comment by ginev** [comment]
@shiamalon - this issue is Android related. Please open a new thread using the Issue Reporting Template to provide more details so that we can investigate. A project to reproduce the issue would be very helpful.

**Comment by tsonevn** [comment]
closing due to inactivity
