### ISSUE TITLE
No databinding in Angular RadListView header and footer.

### ISSUE THREAD

**Issue by RobertGardner** [telerik/nativescript-ui-feedback#207]
If I use a header and/or footer in RadListView with Angular (using the tkListViewHeader/tkListViewFooter directives), data binding does not work in them, though it does in the list items (using tkListItemTemplate).j

For example, this element inside a header will render:
```
<Label text="123"></Label>
```
but this one will not (but it will in the main list):
```
<Label [text]="123"></Label>
```

I found someone with a similar issue on StackOverflow (43733996) but it has not been answered.
(http://stackoverflow.com/questions/tagged/nativescript)?

Issue #158 looks like it was reporting this issue, but it got sidetracked on a styling problem that is not related to this, and was closed.

This is on iOS, I have not been able to try it on Android.

- **Progress NativeScript UI version:** 2.0.1
- **CLI:** 3.0.3
- **Cross-platform modules:** 3.0.1
- **Runtime(s):** tns-ios 3.0.1
- **Other Plugin(s):** I'm using the firebase and videoplayer plugins.

The RadListView snippet looks something like this:
```
<RadListView [items]="items">
      <ng-template tkListItemTemplate let-item="item">
        <StackLayout>
          <GridLayout columns="*,auto,auto">
            <Label col="0" [text]="item.name"></Label>
            <Label col="1" [text]="item.quantity"></Label>
            <Label col="2" [text]="item.price"></Label>
          </GridLayout>
          <StackLayout height="2" backgroundColor="gray"></StackLayout>
        </StackLayout>
      </ng-template>
      <ng-template tkListViewHeader>
        <GridLayout columns="*,auto,auto">
          <Label col="0" text="Name"></Label>
          <Label col="1" text="Qty"></Label>
          <Label col="2" text="Price"></Label>
        </GridLayout>
      </ng-template>
      <ng-template tkListViewFooter>
        <GridLayout columns="*,auto,auto" class="footer">
          <Label col="0" text="Subtotal:"></Label>
          <Label col="1" [text]="count()"></Label>
          <Label col="2" [text]="subtotal()"></Label>
        </GridLayout>
      </ng-template>
    </RadListView>
```

**Comment by VladimirAmiorkov** [comment]
Hi @RobertGardner ,

Thank you for reporting this to us. I can confirm this is an issue in iOS only and will do our best to resolve it as soon as possible.

**Comment by dotnetdreamer** [comment]
@VladimirAmiorkov  any update on this ? is it fixed ?

**Comment by RobertGardner** [comment]
Yes, it was fixed in 3.0.0.

**Comment by alqabali** [comment]
i can confirm that this issue is still exists on version 7.0.4 using ios .

**Comment by VladimirAmiorkov** [comment]
Hi @alqabali ,

I tested this issue and was not able to reproduce it on my side. Can you verify that you have setup your bindings correctly. Here is a playground demo that shows how to binding the header/footer templates to your Angular component: https://play.nativescript.org/?template=play-ng&id=7SD0S5
