### ISSUE TITLE
dataform crash - hidden=true causes undefined error on ios

### ISSUE THREAD

**Issue by recon472** [telerik/nativescript-ui-feedback#371]
## Please, provide the details below:
on ios, when I create new dataform in xml and apply a simple datasource via the code-behind file, if I set the EntityProperty or PropertyGroup hidden=true, app crashes:

file:///app/tns_modules/nativescript-pro-ui/dataform/dataform.js:182:81: JS ERROR TypeError: undefined is not an object (evaluating 'entityProperty.editor.ios')

works fine on android

### Did you verify this is a real problem by searching ...

found similar issue, looks like it's still not resolved: https://www.telerik.com/forums/tkpropertygroup-not-working-on-ios

### Which platform(s) does your issue occur on?
iOS

### Please provide the following version numbers that your issue occurs with:
CLI: 3.3.0
Cross-platform modules: 3.3.0
Runtime(s): 3.3.0
Plugin(s):
"nativescript-pro-ui": "3.1.4",
"nativescript-sqlite": "1.1.11",
"nativescript-theme-core": "1.0.4",
"tns-core-modules": "3.3.0"
Xcode: 9.0.1

### Please tell us how to recreate the issue in as much detail as possible.
1. Start the application ...

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.

<df:RadDataForm id="myDataForm" source="{{ lesson }}" >
        <df:RadDataForm.groups>
            <df:PropertyGroup collapsible="true" name="Hidden" hidden="true">
                <df:PropertyGroup.properties>
                    <df:EntityProperty name="params"/>
                    <df:EntityProperty name="table"/>
                </df:PropertyGroup.properties>
            </df:PropertyGroup>
        </df:RadDataForm.groups>
    </df:RadDataForm>

dataSource = {
    params: "blabla",
    table: "hahaha",
    name: "lol"
}

page.bindingContext = {
    lesson: dataSource
}

**Comment by tsonevn** [comment]
Hi @recon472,
 Thank you for contacting us. 
I tested the described scenario while using the following [example](https://github.com/telerik/nativescript-ui-samples/blob/release/sdk/app/dataform/layouts/grid-layout.xml), however, was unable to recreate an issue with the hidden property. 
It would help if you could provide sample project, which could be debugged locally.

In the meantime, you could try to upgrade the `nativescript-pro-ui` version to the latest available one - 3.2.0.

**Comment by recon472** [comment]
@tsonevn thanks for taking the time. Updating to 3.2.0 didn't help, here's the redacted version of the project. 

https://github.com/recon472/ns-dataform-error-hidden

**Comment by tsonevn** [comment]
Hi @recon472,
Thank you for the attached sample project.
I tested it on my side and was able to recreate the problem, on my side, while using the hidden property. 
As a workaround, you could specify the editor type as it is shown below, which will allow you to set up the hidden property, without the problem.

```
<df:EntityProperty.editor>
                            <df:PropertyEditor type="Text" />
                        </df:EntityProperty.editor>
                    </df:EntityProperty>
                    <df:EntityProperty name="table">
                    <df:EntityProperty.editor>
                            <df:PropertyEditor type="Text" />
                        </df:EntityProperty.editor>
                    </df:EntityProperty>
                    <df:EntityProperty name="sort">
                    <df:EntityProperty.editor>
                            <df:PropertyEditor type="Text" />
                        </df:EntityProperty.editor>
                    </df:EntityProperty>
                    <df:EntityProperty name="_observers">
                    <df:EntityProperty.editor>
                            <df:PropertyEditor type="Text" />
                        </df:EntityProperty.editor>
                    </df:EntityProperty>
```
For further info, you could keep track on the issue.

**Comment by recon472** [comment]
@tsonevn Thank you, the suggested workaround works for me. Happy to help :)

**Comment by Natalia-Hristova** [comment]
@recon472 

This issue is fixed and will be available in the next official release of the plugin. 
You can test it out before that with the "next" version of the `nativescript-pro-ui` plugin. Simply install that version of the plugin: `tns plugin add nativescript-pro-ui@next` or reference it in your package.json like this `nativescript-pro-ui:"next"`

**Comment by simranraza** [comment]
I am still facing this this issue while setting the hidden attribute to variable on a 'PropertyGroup'.

`<TKPropertyGroup tkDataFormGroups collapsible="false" name="MyGroup" hidden="{{testVar}}" index="6">`

**Comment by simranraza** [comment]
This problem is on IOS only, I get the following error...

ERROR TypeError: null is not an object (evaluating 'nativeGroup.hidden = data.value')

**Comment by tsonevn** [comment]
Hi @simranraza,
I tested hidden property in our[ sample application](https://github.com/telerik/nativescript-ui-samples-angular/tree/release/sdkAngular/app/dataform/events), however, was unable to recreate the reported issue. The In the example I just replace the code in the dataform-events.component.html file with the following one:
```
<GridLayout tkExampleTitle tkToggleNavButton rows="auto, *">
    <Label margin="12" [text]="eventsText" row="0"></Label>
    <!-- >> angular-dataform-commit-cancel-html -->
    <RadDataForm [source]="person" marginTop="50" row="1" (groupExpanded)="dfGroupExpanded($event)" (groupCollapsed)="dfGroupCollapsed($event)"
        (propertyCommit)="dfPropertyCommit($event)" (propertyCommitted)="dfPropertyCommitted($event)">
        <!-- << angular-dataform-commit-cancel-html -->
        <TKPropertyGroup tkDataFormGroups collapsible="true" hidden="true" name="Main Info">
            <TKEntityProperty tkPropertyGroupProperties name="name"></TKEntityProperty>
            <TKEntityProperty tkPropertyGroupProperties name="age"></TKEntityProperty>
            <TKEntityProperty tkPropertyGroupProperties name="email"></TKEntityProperty>
        </TKPropertyGroup>
        <TKPropertyGroup tkDataFormGroups collapsible="true" name="Address">
            <TKEntityProperty tkPropertyGroupProperties name="city"></TKEntityProperty>
            <TKEntityProperty tkPropertyGroupProperties name="street"></TKEntityProperty>
            <TKEntityProperty tkPropertyGroupProperties name="streetNumber"></TKEntityProperty>
        </TKPropertyGroup>
    </RadDataForm>
</GridLayout>
```

Please provide more info about your environment(modules, runtime, CLI, nativescript-pro-ui versions) as well as a sample project, which could be used for debugging.

**Comment by Shantanu-Kotambkar** [comment]
This throws an error for me saying Module 'ui/rad-data-form' not found for element 'RadDataForm'.

**Comment by yalva** [comment]
I'm facing this error as well

CONSOLE ERROR file:///app/tns_modules/tns-core-modules/trace/trace.js:165:30: Binding: Binding error while setting property source of RadDataForm<patientForm>@file:///app/my-page.xml:10:13;: TypeError: null is not an object (evaluating 'nativeGroup.hidden = true')

This is my group declaration in XML file
<df:PropertyGroup collapsible="true" name="myGroup" hidden="{{ editMode }}">

It works fine on Android.

**Comment by jessorlisa** [comment]
Sadly this still seems to be an issue two years later? At least with Angular, I did not test the other flavours.

Steps to reproduce:
- Get the samples project: https://github.com/ProgressNS/nativescript-ui-samples-angular
- cd dataform
- open `dataform/app/examples/groups/dataform-groups.component.html` and change the `hidden` attribute of the **second group** to true. **Important and strange: It works fine with the first group!**
- tns run ios
- navigate to the "Groups" example
- crash with: `file: node_modules/nativescript-ui-dataform/ui-dataform.ios.js:908:0: JS ERROR TypeError: null is not an object (evaluating 'nativeGroup.hidden = true')`

Any ideas?
