### ISSUE TITLE
AutoCompleteTextView SuggestionView not visible in iOS modal

### ISSUE THREAD

**Issue by jevenson** [telerik/nativescript-ui-feedback#379]
### Did you verify this is a real problem by searching [Stack Overflow](http://stackoverflow.com/questions/tagged/nativescript)?
_Yes_

### Tell us about the problem
I'm trying to use the AutoCompleteTextView in a modal. When text is inputted, no results are returning, but the suggestionViewBecameVisible event is still firing. When I move the component out of the modal and onto a regular page, the results are visible.

Android works as expected.

### Which platform(s) does your issue occur on?
_iOS_

### Please provide the following version numbers that your issue occurs with:
- **Progress NativeScript UI version:** 3.1.4
- **CLI:** 3.2.1
- **Cross-platform modules:** 3.2.0
- **Runtime(s):** 3.2.0

### Please tell us how to recreate the issue in as much detail as possible.
1. Start the application
1. Launch Modal with AutoCompleteTextView
1. Start typing in input
1. Observe no results are displayed

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
AutocompeteModalComponent is the component that is launched in the modal.
AutocompleteModalComponent launches the modal.
https://gist.github.com/jevenson/02ad082c4be8367427dd995643c0d14b

**Comment by NickIliev** [comment]
@jevenson  confirming this as a bug.
Steps to reproduce - use [this test application](https://github.com/NickIliev/NS-Issues/tree/master/nativescript-ui-feedback/issue_379)

- the AutoCompleteTextView in the initial page is showing the suggestion view as expected.
- the same code in a modal page is not showing the suggestion view at all.

**Comment by NickIliev** [comment]
Confirmed as not resolved via **next** version of the plugin

**Comment by adouglas0363** [comment]
I just ran into this same issue. Do we have an eta on when we could expect to see this fixed?

**Comment by nmongiya** [comment]
While looking into code I was suspecting that it could be `updateHeight` issue but when I tried this in my app it looks like z-index issue. As Suggestion View became visible once I close the model window.

**Comment by tgpetrov** [comment]
Related with: https://github.com/telerik/nativescript-ui-feedback/issues/355

**Comment by zbranzov** [comment]
A fix is released in nativescript-ui-autocomplete@3.9.0. Enjoy!

**Comment by ben-sab** [comment]
@zbranzov this is still an issue (at least on simulators) in iOS with nativescript-ui-autocomplete@3.11.0. It's working fine outside modals but not in modals.

**Comment by romandragan** [comment]
@zbranzov, still occurring for me with `nativescript-ui-autocomplete@6.0.0`.

**Comment by lini** [comment]
Can you make an example that reproduces this behavior (you can use https://play.nativescript.org/)? 
I tried to reproduce the issue with the latest version in iOS and the suggestion list displayed in the modal:
![image](https://user-images.githubusercontent.com/1461621/71673119-8ba2fd80-2d80-11ea-8a51-80c7d937f83a.png)

**Comment by mika-ella** [comment]
hi guys, are you able to find solutions for this? I have the same issue on ios. I am still facing this issue.
