### ISSUE TITLE
[RadListview]: How to get the correct item after Grouping/Sorting/Filtering.

### ISSUE THREAD

**Issue by relez** [telerik/nativescript-ui-feedback#596]
Hi there, how can I get the correct item/group of the list after I use a filter/group/sorting functions in the RadListView? Here is a working example at the Playground. Is there any way to get the final array which is populating the ListView after filtering/grouping/sorting?

[https://play.nativescript.org/?template=play-ng&id=KCpViw&v=5](https://play.nativescript.org/?template=play-ng&id=KCpViw&v=5)

Also, if I use the `getSelectedItems` function and I navigate to another component and return, if I select another item, the previous selection will be erased and will only have the last item, is it an expected behavior?

Thanks!

**Comment by NickIliev** [comment]
@relvis the observed behavior is, in fact, a bug when the data operation functions(sorting, filtering, grouping) are used along with item selection.

The good news is that this issue is already resolved and the fix is included in version 3.5.3 of `nativescript-ui-listview`

[Tested for this example](https://github.com/telerik/nativescript-ui-samples-angular/tree/release/sdkAngular/app/listview/sorting) and the following code changes (to introduce grouping, sorting and filtering aat the same time)

**_listview-data-operations-sorting.component.html_**
```
<GridLayout tkExampleTitle tkToggleNavButton rows="auto, *">
    <StackLayout orientation="horizontal">
        <Button [text]="isEnabled ? 'Disable sorting' : 'Enable sorting'" (tap)="toggleSorting()" ios:margin="5"></Button>
    </StackLayout>
    <RadListView [items]="dataItems" row="1" #myListView selectionBehavior="Press" (itemSelected)="itemSelected($event)" [filteringFunction]="myFilteringFunc" [groupingFunction]="myGroupingFunc" [sortingFunction]="mySortingFunc">
        <ng-template tkListItemTemplate let-item="item">
            <StackLayout orientation="vertical">
                <Label class="nameLabel" [text]="item.name"></Label>
                <Label class="descriptionLabel" [text]="item.description"></Label>
            </StackLayout>
        </ng-template>
    </RadListView>
</GridLayout>
```

**_listview-data-operations-sorting.component.ts_**
```
import { Component, OnInit, ViewChild } from "@angular/core";
import { ObservableArray } from "tns-core-modules/data/observable-array";
import { RadListViewComponent } from "nativescript-ui-listview/angular";
import { DataItem } from "../dataItem";
import { DataItemService } from "../dataItem.service";

enum SortingOrder {
    NSOrderedAscending = -1,
    NSOrderedSame = 0,
    NSOrderedDescending = 1
}

@Component({
    moduleId: module.id,
    selector: "tk-listview-data-operations-sorting",
    providers: [DataItemService],
    templateUrl: "listview-data-operations-sorting.component.html",
    styleUrls: ["listview-data-operations-sorting.component.css"]
})
export class ListViewDataOperationsSortingComponent implements OnInit {
    private _dataItems: ObservableArray<DataItem>;
    private _isEnabled: boolean;
    private _mySortingFunc: (item: any, otherItem: any) => number;
    private _myGroupingFunc: (item: any) => any;
    private _myFilteringFunc: (item: any) => any;

    @ViewChild("myListView") myListViewComponent: RadListViewComponent;

    constructor(private _dataItemService: DataItemService) {
        // >> listview-data-operations-sorting-angular
        this.mySortingFunc = (item: DataItem, otherItem: DataItem) => {
            var res = item.id < otherItem.id ? SortingOrder.NSOrderedAscending : item.id > otherItem.id ? SortingOrder.NSOrderedDescending : SortingOrder.NSOrderedSame;
            return res;
        };

        this.myGroupingFunc = (item: DataItem) => {
            return item.category;
        };

        this.myFilteringFunc = (item: DataItem) => {
            return item.name.includes("Special Item");
        };
        // <<
        // << listview-data-operations-sorting-angular
        this.isEnabled = true;
    }

    ngOnInit() {
        this._dataItems = new ObservableArray<DataItem>(this._dataItemService.getDataOperationsItems());
    }

    get dataItems(): ObservableArray<DataItem> {
        return this._dataItems;
    }

    get isEnabled() {
        return this._isEnabled;
    }

    set isEnabled(value: boolean) {
        this._isEnabled = value;
    }

    get mySortingFunc(): (item: any, otherItem: any) => number {
        return this._mySortingFunc;
    }

    set mySortingFunc(value: (item: any, otherItem: any) => number) {
        this._mySortingFunc = value;
    }

    get myGroupingFunc(): (item: any) => any {
        return this._myGroupingFunc;
    }

    set myGroupingFunc(value: (item: any) => any) {
        this._myGroupingFunc = value;
    }

    get myFilteringFunc(): (item: any) => any {
        return this._myFilteringFunc;
    }

    set myFilteringFunc(value: (item: any) => any) {
        this._myFilteringFunc = value;
    }

    public toggleSorting() {
        let listView = this.myListViewComponent.listView;
        if (!listView.sortingFunction) {
            listView.sortingFunction = this.mySortingFunc;
            this.isEnabled = true;
        } else {
            listView.sortingFunction = undefined;
            this.isEnabled = false;
        }
    }

    itemSelected(args) {
        var item = this._dataItems.getItem(args.index);
        alert(item.name);
        item.selected = true;
    }

}
```

**Comment by relvis** [comment]
Hi @NickIliev, thanks for the quick answer. I updated to 3.5.3 and I am still getting `args.index` based on the original observable array but not the one who is modified inside the RadListView after the filter/group/sort. Is there any way I can get that list which is populating the RadListView?

**Comment by MopheusDG** [comment]
Hi, I'm also having this problem. I'm using JS and when I apply Grouping to my RadListView my observable gets all deformed in the index. In my case I use first letter to group and when it creates the separators, the index is being assigned to the separator, so the "A" separator is index 0 for example, and the first item is index 1, so if I click the A separator, I get the first record information, and so on....

Also, is it possible to make the separators (group items) to be ignored by default ? Makes no sense to be able to do onitemselect on them, right ?

Any ideas or workaround for JS please ? Thanks...

**Comment by tigrenok00** [comment]
Same for me in 3.5.11 :(

**Comment by VladimirAmiorkov** [comment]
Hi @tigrenok00 @MopheusDG ,

Can you share a runnable project that reproduces this issue with the latest version of the nativescript-ui-listview plugin?

**Comment by MopheusDG** [comment]
Actually, in my case, I was using "itemTap" instead of "itemSelected". Not sure why, but "itemTap" when the list is grouped, was getting wrong index, but when switched to "itemSelected" is working fine.

So for me, if LIST is NOT GROUPED, "itemTap" and "itemSelected" both work fine.
When the LIST is GROUPED, "itemTap" let's me TAP on the group separators and get's me wrong indexes, but "itemSelected" works as expected.

Is this the expected behaviour ?

**Comment by tigrenok00** [comment]
As for me, I am experiencing this in the Swipe events, as mentioned in the referenced issue.

**Comment by zbranzov** [comment]
We did some fixes in nativescript-ui-listview@3.6.1. Would check whether your issue persist?
